Transporte2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('alunos.urls', namespace='alunos', app_name='alunos')),
]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alunos/urls.py
from django.conf.urls import url 
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
	url(r'^index', views.index, name= 'index'),  
	url(r'^login', views.do_login, name= 'login'), 
	url(r'^logout', views.do_logout, name= 'logout'),
	url(r'^novo-aluno', login_required(views.NovoAluno.as_view(success_url='/index')), name= 'novo-aluno'),
	url(r'^novo-chamado', login_required(views.NovoChamado.as_view(success_url='/index')), name= 'novo-chamado'),
	url(r'^aluno/(?P<pk>[-\w]+)/$', login_required(views.AlunoView.as_view()), name='aluno-detalhe'),
	url(r'^(?P<pk>[-\w]+)/delete$', login_required(views.AlunoDelete.as_view()), name='aluno-delete'),
	url(r'^documento/(?P<documentoTipo>[\w\.%+-]+)/(?P<doc_id>\w+)/(?P<bool>\w+)/$', views.modifica_documento, name='modifica-documento'),
	url(r'^(?P<pk>[-\w]+)/update$', login_required(views.AlunoUpdate.as_view(success_url='/index')), name='aluno-update'),
	url(r'^(?P<aluno_id>\w+)/apagar/$', views.apaga_aluno, name='apaga-aluno'),
]

alunos/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

# Create your models here.

class TipoChamado(models.Model):
    nome = models.CharField('Nome do chamado', max_length=100)

    def __str__(self):
        return self.nome.encode('utf-8')


class DiasSemana(models.Model):
    nome = models.CharField('Dia', max_length=20)
    

    def __str__(self):
        return self.nome.encode('utf-8')


class Cidade(models.Model):
    nome = models.CharField('Cidade', max_length=25)

    def __str__(self):
        return self.nome.encode('utf-8')


class Aluno(models.Model):

    TURNO_CHOICES = (
        ('M', 'Manhã'),
        ('T', 'Tarde'),
        ('N', 'Noite'),
        ('MT', 'Manhã / Tarde'),
        ('MTN', 'Manhã / Tarde / Noite'),
        ('TN', 'Tarde / Noite'),
        ('MN', 'Manhã / Noite')

    )


    SITUACAO_CHOICES = (
        ('N', 'Novo'),
        ('R', 'Renovação')
    )

    SERVICOS_CHOICES = (
        ('FIES', 'FIES'),
        ('PROUNI', 'PROUNI'),
        ('PEP', 'PEP'),
        ('OUTROS', 'OUTRO (COLOCAR NA OBSERVAÇÃO)'),
        ('NENHUM', 'NENHUM')
    )


    # TELEFONES
    # Formato do telefone aceito: (99) 99999-9999
    # Outro formato aceito: (99) 9999-9999
    # regex="^(\(11\) [9][0-9]{4}-[0-9]{4})|(\(1[2-9]\) [5-9][0-9]{3}-[0-9]{4})|(\([2-9][1-9]\) [5-9][0-9]{3}-[0-9]{4})$", error_message=("Por favor, verifique o número informado.")
    # Adicionar um método que vai veirificar se o registro já existe no banco

    nome = models.CharField('Nome completo', max_length=100)
    rg = models.CharField('RG', max_length=11)
    titulo = models.CharField('Título de eleitor', max_length=50)
    cpf = models.CharField('CPF', max_length=15, blank=False)
    email = models.CharField('E-mail', max_length=34)
    cep = models.IntegerField('CEP', blank=False)
    endereco = models.CharField('Endereço', max_length=128)
    bairro = models.CharField('Bairro', max_length=20)
    mora_com_pais = models.BooleanField('Mora com os pais?')
    telefone_fixo =  models.CharField('Telefone fixo', max_length=13)
    telefone_movel = models.CharField('Telefone celular', max_length=13)
    registro_academico = models.CharField('Registro Acadêmico', max_length=20)
    tem_whatsapp = models.BooleanField('Tem Whatsapp?')
    inst_ensino_nome = models.CharField('Instituição de ensino', max_length=30)
    inst_ensino_cicade = models.ForeignKey(Cidade)
    curso = models.CharField('Curso', max_length=25)
    duracao_curso = models.IntegerField('Duração do curso (Anos)')
    semestre_matriculado = models.BooleanField('Semestre atual matriculado')
    turno = models.CharField('Turno', max_length=2, choices=TURNO_CHOICES)
    servicos = models.CharField('Serviços', max_length=7, choices=SERVICOS_CHOICES, default='NENHUM')
    situacao = models.CharField('Situação', max_length=2, choices=SITUACAO_CHOICES)
    dias_utilizacao = models.ManyToManyField(DiasSemana)
    is_active = models.BooleanField('Está ativo?', default=True, blank=True)
    foto = models.FileField(blank=True, null=True)


    class Meta:
        ordering = ('nome', 'cpf', 'is_active')
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'


    def __unicode__(self):
        return self.nome

    def __str__(self):
        return self.nome + ' - ' + self.cpf


class Chamado(models.Model):
    tipo = models.ForeignKey(TipoChamado)
    usuario = models.ForeignKey(User)
    aluno = models.ForeignKey(Aluno)
    data = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField('Título', max_length=100, default='')
    texto = models.TextField(max_length=1000)

    def __str__(self):
        return self.aluno.nome + ' - ' + str(self.data)


# Vai retornar a pasta com o id do usuario
def user_directory_path(instance, filename):
    return 'documentos_aluno_{0}/{1}'.format(instance.aluno.id, filename)


class DocumentoCPF(models.Model):
    aluno = models.ForeignKey(Aluno)
    arquivo = models.FileField(upload_to=user_directory_path)
    is_valid = models.BooleanField(default=False)
    data_inclusao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.aluno.nome

    def __unicode__(self):
        return self.aluno.nome

    class Meta:
        verbose_name = 'Documentação CPF'
        verbose_name_plural = 'Documentos - CPF'

class DocumentoRG(models.Model):
    aluno = models.ForeignKey(Aluno)
    arquivo = models.FileField(upload_to=user_directory_path)
    is_valid = models.BooleanField(default=False)
    data_inclusao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.aluno.nome

    class Meta:
        verbose_name = 'Documentação RG'
        verbose_name_plural = 'Documentos - RG'

alunos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from alunos.models import Aluno, Chamado

class AlunoForm(forms.ModelForm):

	class Meta():

		model = Aluno
		fields = [
			'nome', 'rg', 'titulo', 'cpf', 'email', 'cep', 'endereco', 'bairro', 'mora_com_pais',
			'telefone_fixo', 'telefone_movel', 'registro_academico', 'tem_whatsapp', 'inst_ensino_nome',
			'inst_ensino_cicade', 'curso', 'duracao_curso', 'semestre_matriculado', 'turno', 'servicos',
			'situacao', 'dias_utilizacao', 'foto'
		]
		widgets = {
			'nome' : forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'Nome completo'}),
			'rg' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'RG'}),
			'titulo' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Título de eleitor'}),
			'cpf' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Número do CPF'}),
			'email' : forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'E-mail'}),
			'cep' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'CEP'}),
			'endereco' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Endereço'}),
			'bairro' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Bairro'}),
            'mora_com_pais' : forms.CheckboxInput(attrs={'class' : 'form-control flat'}),
			'telefone_fixo' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Telefone fixo'}),
			'telefone_movel' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Telefone móvel'}),
			'registro_academico' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Registro acadêmico'}),
			'tem_whatsapp' : forms.CheckboxInput(attrs={'class' : 'form-control flat'}),
			'inst_ensino_nome' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Instituição de ensino'}),
			'inst_ensino_cicade' : forms.Select(attrs={'class' : 'form-control'}),
			'curso' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Curso'}),
			'duracao_curso' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Duração do curso (anos)'}),
			'semestre_matriculado' : forms.CheckboxInput(attrs={'class' : 'form-control flat'}),
			'turno' : forms.Select(attrs={'class' : 'form-control'}),
			'servicos' : forms.Select(attrs={'class' : 'form-control'}),
            'situacao' : forms.Select(attrs={'class' : 'form-control'}),
            'dias_utilizacao' : forms.CheckboxSelectMultiple(attrs={'class' : 'form-control flat'}),
            'foto' : forms.FileInput()
		}


class ChamadoForm(forms.ModelForm):

	class Meta():

		model = Chamado
		fields = [
			'tipo',  'aluno', 'titulo', 'texto' 
		]
		widgets = {
			'tipo' : forms.Select(attrs={'class' : 'form-control'}),
			#'usuario' : forms.Select(attrs={'class' : 'form-control'}),
			'aluno' : forms.Select(attrs={'class' : 'form-control'}),
			'titulo' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Título'}),
			'texto' : forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Texto', 'rows': 11})
		}

alunos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Aluno, Chamado, DiasSemana, DocumentoCPF, DocumentoRG
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.core.urlresolvers import reverse_lazy
from .forms import AlunoForm, ChamadoForm
from django.views import View
# Create your views here.


class AlunoUpdate(UpdateView):
	model = Aluno
	template_name = 'app/update_aluno.html'
	form_class = AlunoForm


"""
	Método que vai colocar o is_active do aluno para false
"""
@login_required
def apaga_aluno(request, aluno_id):
	aluno = Aluno.objects.filter(pk=aluno_id)
	print (aluno)
	for field in aluno:
		field.is_active = False
		field.save()
	return redirect('/index')


""" 
	Método que vai modificar o status do documento
"""
@login_required
def modifica_documento(request, documentoTipo, doc_id, bool):
	print (bool)
	tipo = eval(documentoTipo.encode('utf8'))

	documento_id = int(doc_id)
	documento = tipo.objects.filter(pk=documento_id)
	for doc in documento:
		doc.is_valid = bool
		doc.save()
	return redirect('/index')


@login_required
def index(request):
	user = request.user
	alunos = Aluno.objects.all()
	alunos_manha = Aluno.objects.filter(turno='M')
	alunos_tarde = Aluno.objects.filter(turno='T')
	alunos_noite = Aluno.objects.filter(turno='N')
	count_alunos = alunos.count

	dict = {
		'user' : user,
		'alunos' : alunos,
		'count_alunos' : count_alunos,
		'count_alunos_manha' : alunos_manha.count,
		'count_alunos_tarde' : alunos_tarde.count,
		'count_alunos_noite' : alunos_noite.count
	}

	return render(request, 'app/index.html', dict)


def do_login(request):
	if(request.method == 'POST'):
		user = authenticate(username= request.POST['username'], password=request.POST['password'])
		if user is not None:
			login(request, user)
			return redirect('/index')
	return render(request, 'app/login.html')


def do_logout(request):
	logout(request)
	return redirect('/login')


class NovoAluno(CreateView):
	model = Aluno
	template_name = 'app/cadastro_aluno.html'
	form_class = AlunoForm


class NovoChamado(CreateView):
	model = Chamado
	template_name = 'app/cadastro_chamado.html'
	form_class = ChamadoForm

	def form_valid(self, form):
		form.instance.usuario = self.request.user
		return super(NovoChamado, self).form_valid(form)


class AlunoView(DetailView):
	model = Aluno
	template_name = 'app/detalhe_aluno.html'

	def get_context_data(self, **kwargs):
		context = super(AlunoView, self).get_context_data(**kwargs)
		context['chamados'] = Chamado.objects.filter(aluno = context['aluno'].id).order_by('-data')
		context['dias_utilizacao'] = DiasSemana.objects.filter(aluno=context['aluno'].id).order_by('-id')
		context['documento_cpf'] = DocumentoCPF.objects.filter(aluno=context['aluno'].id)
		context['documento_rg'] = DocumentoRG.objects.filter(aluno=context['aluno'].id)
		if context['aluno'].turno == 'M':
			context['turno_nome'] = 'Manhã'
		elif context['aluno'].turno == 'T':
			context['turno_nome'] = 'Tarde'
		elif context['aluno'].turno == 'N':
			context['turno_nome'] = 'Noite'
		elif context['aluno'].turno == 'MT':
			context['turno_nome'] = 'Manhã / Tarde'
		elif context['aluno'].turno == 'MTN':
			context['turno_nome'] = 'Manhã / Tarde / Noite'
		elif context['aluno'].turno == 'TN':
			context['turno_nome'] = 'Tarde / Noite'
		elif context['aluno'].turno == 'MN':
			context['turno_nome'] = 'Manhã / Noite'
		return context


class AlunoDelete(DeleteView):
	model = Aluno
	success_url = reverse_lazy('alunos:index')

	def get(self, *args, **kwargs):
		return self.post(*args, **kwargs)

alunos/templates/app/cadastro_chamado.html
{% extends "app/base_site.html" %}

{% block title %} Novo Aluno {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
      <div class="">
        <div class="page-title">
          <div class="title_left">
            <h3>Cadastros</h3>
          </div>

         
        </div>

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Cadastrar aluno</h2>
                <ul class="nav navbar-right panel_toolbox">
                  <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                  </li>
                </ul>
                <div class="clearfix"></div>
              </div>
              <div class="x_content">

                <div class="row">

                  <form action="{% url 'alunos:novo-chamado' %}" method="POST">
                    {% csrf_token %}
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                      <div class="form-group">
                        <label>Tipo do chamado</label>
                        {{ form.tipo }}
                      </div>
                    </div>

                    <div class="col-md-6 col-sm-12 col-xs-12 form-group">
                      <div class="form-group">
                        <label>Aluno</label>
                        {{ form.aluno }}
                      </div>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                      <div class="form-group">
                        <label>Título</label>
                        {{ form.titulo }}
                      </div>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12 form-group">
                      <div class="form-group">
                        <label>Texto</label>
                        {{ form.texto }}
                      </div>
                    </div>


                   <div class="ln_solid"></div>
                    <div class="form-group">
                      <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-5">
                        <button type="submit" class="btn btn-success">Salvar</button>
                      </div>
                    </div>
                  
                  </form>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

alunos/templates/app/footer.html
<div class="pull-right">
  Controle do Transporte Universitário - Desenvolvido por:  <a href="http://github.com/ttibau" target="_blank">Thiago Tibau Salgado <span class="fa fa-code"></span></a>
</div>
<div class="clearfix"></div>

alunos/templates/app/index.html
{% extends "app/base_site.html" %} {% block title %} Plain Page {% endblock title %} {% block stylesheets %} {{ block.super }} {% endblock stylesheets %} {% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Página inicial</h3>
      </div>

      <div class="title_right">
        <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                  <button class="btn btn-default" type="button">Go!</button>
                </span>
          </div>
        </div>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Informações</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="row">
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-globe"></i>
                  </div>
                  <div class="count">{{count_alunos}}</div>

                  <h3>Total</h3>
                  <p>Total de alunos cadastrados.</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-sun-o"></i>
                  </div>
                  <div class="count">{{count_alunos_manha}}</div>

                  <h3>Manhã</h3>
                  <p>Alunos no turno da manhã.</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-flash"></i>
                  </div>
                  <div class="count">{{count_alunos_tarde}}</div>

                  <h3>Tarde</h3>
                  <p>Alunos no turno da tarde.</p>
                </div>
              </div>
              <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="tile-stats">
                  <div class="icon"><i class="fa fa-moon-o"></i>
                  </div>
                  <div class="count">{{count_alunos_noite}}</div>

                  <h3>Noite</h3>
                  <p>Aunos no turno da noite.</p>
                </div>
              </div>

              <!-- FIM DOS WIDGETS DOS TURNOS -->
              <!-- TABELA -->
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Últimos alunos <small>Últimos alunos cadastrados</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>#</th>
                          <th>Nome</th>
                          <th>Telefone Celular</th>
                          <th>E-mail</th>
                          <th>Instituição</th>
                          <th>Ações</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for aluno in alunos %}
                      {% if aluno.is_active == True %}
                        <tr>
                          <th scope="row">{{aluno.id}}</th>
                          <td><a href="{% url 'alunos:aluno-detalhe' aluno.id %}">{{aluno.nome}}</a></td>
                          <td>{{aluno.telefone_movel}}</td>
                          <td>{{aluno.email}}</td>
                          <td>{{aluno.inst_ensino_nome}}</td>
                          <td>
                            <a href="{% url 'alunos:aluno-detalhe' aluno.id %}" ><span class="fa fa-eye"></span></a> |
                            <a href="{% url 'alunos:aluno-update' aluno.id %} "><span class="fa fa-edit"></span></a> |
                            <a  href="{% url 'alunos:apaga-aluno' aluno.id %}"><i class="fa fa-trash"></i></a>
                          </td>
                        </tr>
                        {% endif %}
                      {% endfor %}
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>
            </div>
            <!-- fim da tabela -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %} {% block javascripts %} {{ block.super }}
<script src="/static/vendors/Chart.js/dist/Chart.min.js"></script>
<!-- jQuery Sparklines -->
<script src="/static/vendors/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
<!-- easy-pie-chart -->
<script src="/static/vendors/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js"></script>
{% endblock javascripts %}

alunos/templates/app/login.html
{% extends "app/base_site.html" %}

{% block title %} Login {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
  <!-- Animate.css -->
  <link href="/static/vendors/animate.css/animate.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block body_class %}login{% endblock body_class %}

{% block body %}
  <div>
    <a class="hiddenanchor" id="signup"></a>
    <a class="hiddenanchor" id="signin"></a>

    <div class="login_wrapper">
      <div class="animate form login_form">
        <section class="login_content">
          <form method="post" action="{% url 'alunos:login' %}">
          {% csrf_token %}
            <h1><span class="fa fa-lock"></span> Entrar</h1>
            <div>
              <input type="text" class="form-control" placeholder="Usuário" name="username" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Senha" name="password" required="" />
            </div>
            <div>
              <input class="btn btn-default submit" href="index.html" value="Entrar" type="submit">
              <a class="reset_pass" href="#">Esqueceu a senha?</a>
            </div>

            <div class="clearfix"></div>

            <div class="separator">
             

              <div class="clearfix"></div>
              <br />

              <div>
                <h1><i class="fa fa-bus"></i> Transporte Universitário!</h1>
                <p>©2017 Central de Controle do Transporte Universitário -  Desenvolvido por Thiago Tibau</p>
              </div>
            </div>
          </form>
        </section>
      </div>

      <div id="register" class="animate form registration_form">
        <section class="login_content">
          <form>
            <h1>Create Account</h1>
            <div>
              <input type="text" class="form-control" placeholder="Username" required="" />
            </div>
            <div>
              <input type="email" class="form-control" placeholder="Email" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Password" required="" />
            </div>
            <div>
              <a class="btn btn-default submit" href="index.html">Submit</a>
            </div>

            <div class="clearfix"></div>

            <div class="separator">
              <p class="change_link">Already a member ?
                <a href="#signin" class="to_register"> Log in </a>
              </p>

              <div class="clearfix"></div>
              <br />

              <div>
                <h1><i class="fa fa-paw"></i> Gentelella Alela!</h1>
                <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>
              </div>
            </div>
          </form>
        </section>
      </div>
    </div>
  </div>
{% endblock body %}

alunos/templates/app/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="index.html" class="site_title"><i class="fa fa-bus"></i> <span>Transporte Universitário</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    <div class="profile_pic">
      <img src="/static/images/img.jpg" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
      <span>Bem-vindo,</span>
      <h2>{{user.first_name}} (<a href="{% url 'alunos:logout' %}">Sair</a>)</h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>Menu</h3>
      <ul class="nav side-menu">
        <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'alunos:index' %}">Informações</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-users"></i> Alunos <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="#">Todo os alunos</a></li>
            <li><a href="form.html">Alunos Niterói</a></li>
            <li><a href="form_advanced.html">Alunos São Gonçalo</a></li>
            <li><a href="form_validation.html">Alunos Niterói - Manhã</a></li>
            <li><a href="form_wizards.html">Alunos Niterói - Tarde</a></li>
            <li><a href="form_upload.html">Alunos Niterói - Noite</a></li>
            <li><a href="form_buttons.html">Alunos São Gonçalo - Manhã</a></li>
            <li><a href="form_buttons.html">Alunos São Gonçalo - Tarde</a></li>
            <li><a href="form_buttons.html">Alunos São Gonçalo - Noite</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-wechat"></i> Chamados <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="#">Todo os chamados</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-plus-square-o"></i> Cadastros <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'alunos:novo-aluno' %}">Cadastrar aluno</a></li>
            <li><a href="{% url 'alunos:novo-chamado' %}">Abrir novo chamado</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-list-alt"></i> Frequências <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="tables.html">Tables</a></li>
            <li><a href="tables_dynamic.html">Table Dynamic</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
  <div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
      <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
      <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
      <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
      <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
  </div>
  <!-- /menu footer buttons -->
</div>